leftnav:
- identifier: 9f6e3e3c-0bda-4f8f-9d7c-9db2dd1cf179
  name: Introductory Programming Courses
  pageRef: /external-resources/introductory-programming-courses_9f6e3e3c-0bda-4f8f-9d7c-9db2dd1cf179
  weight: 10
- identifier: 302bf23a-1209-419a-8c74-48b2573e440a
  name: Archived DSpace Course
  pageRef: /external-resources/archived-d-space-course_302bf23a-1209-419a-8c74-48b2573e440a
  weight: 20
